### ISSUE TITLE
Document how to read routing data in a component

### ISSUE THREAD

**Issue by zejji** [solidui/solid-app-router#12]
Take for example the route "/users/:id/orders?order=popular".

How does one read the following inside the component which is routed to?:
- the route parameters (:id)
- the query parameters (order=popular)

I've been trying to read through the source code and at first glance it looks like these ought to be set as props on the component, but it's not proving to a very productive exercise.

Would you be able to provide a little more documentation regarding the basic usage?

**Comment by bramaudi** [comment]
Have you try to use router hook like this:

```js
import { useRouter } from "solid-app-router"

// inside component
const [router] = useRouter()
```

**Comment by zejji** [comment]
@bramaudi - Many thanks - that's just what I was looking for!

The following works fine:
``` ts
import { useRouter } from "solid-app-router";

const WidgetPage = () => {
    const [router]: any = useRouter();
    return (
    <div>
      <p>
        This is the widget page. Widget is is {router.params.id}
      </p>
    </div>
  )
};

export default WidgetPage;
```
